// =============================================================================
// Generated by packages/simulator/src/train.ts on 2026-06-03
// =============================================================================
// Logistic-regression classifier for real-time shill-bid scoring.
//
// Fit by batch gradient descent (alpha=0.2, lambda=0.01, epochs=10000) on the
// TRAIN partition of the simulator corpus. sellerCoOccurrence is grounded in
// the real auction owner (see packages/simulator/src/dataset.ts). Held-out
// test metrics and the threshold ROC sweep are reported by eval.ts.
//
// Train-set performance (threshold 0.5):
//   Accuracy 93.18% | Precision 0.9459 | Recall 0.9722 | F1 0.9589

import { FeatureVector, ClassifierWeights, NormParams } from './fraud.types';

export const WEIGHTS: ClassifierWeights = {
  intercept: 2.7951,
  responseTimeMs: -0.2332,
  bidFrequencyPerMin: -0.5218,
  incrementRatio: 0.01,
  reciprocityScore: -0.2408,
  sellerCoOccurrence: 2.5006,
};

export const NORM_PARAMS: NormParams = {
  mean: {
    responseTimeMs: 6519.0455,
    bidFrequencyPerMin: 0.1780,
    incrementRatio: 1.3182,
    reciprocityScore: 0.4318,
    sellerCoOccurrence: 2.2955,
  },
  std: {
    responseTimeMs: 5224.8805,
    bidFrequencyPerMin: 0.1269,
    incrementRatio: 0.9237,
    reciprocityScore: 0.3559,
    sellerCoOccurrence: 0.9190,
  },
};

export const SCORE_THRESHOLD = 0.5;

function sigmoid(x: number): number {
  return 1 / (1 + Math.exp(-x));
}

function normalise(features: FeatureVector, params: NormParams): FeatureVector {
  const clamp = (v: number, std: number) =>
    std > 0 ? Math.max(-4, Math.min(4, v / std)) : 0;
  return {
    responseTimeMs: clamp(features.responseTimeMs - params.mean.responseTimeMs, params.std.responseTimeMs),
    bidFrequencyPerMin: clamp(features.bidFrequencyPerMin - params.mean.bidFrequencyPerMin, params.std.bidFrequencyPerMin),
    incrementRatio: clamp(features.incrementRatio - params.mean.incrementRatio, params.std.incrementRatio),
    reciprocityScore: clamp(features.reciprocityScore - params.mean.reciprocityScore, params.std.reciprocityScore),
    sellerCoOccurrence: clamp(features.sellerCoOccurrence - params.mean.sellerCoOccurrence, params.std.sellerCoOccurrence),
  };
}

/** Score a feature vector. Returns a probability in [0, 1]. */
export function score(features: FeatureVector): number {
  const z = normalise(features, NORM_PARAMS);
  const logit =
    WEIGHTS.intercept +
    WEIGHTS.responseTimeMs * z.responseTimeMs +
    WEIGHTS.bidFrequencyPerMin * z.bidFrequencyPerMin +
    WEIGHTS.incrementRatio * z.incrementRatio +
    WEIGHTS.reciprocityScore * z.reciprocityScore +
    WEIGHTS.sellerCoOccurrence * z.sellerCoOccurrence;
  return sigmoid(logit);
}

/** Human-readable explanation of the contributing features for a flag. */
export function explain(features: FeatureVector, s: number): string {
  const parts: string[] = [];
  if (features.responseTimeMs < 500 && features.responseTimeMs > 0) {
    parts.push(`response time ${features.responseTimeMs}ms (bot-speed)`);
  }
  if (features.bidFrequencyPerMin > 2) {
    parts.push(`${features.bidFrequencyPerMin.toFixed(1)} bids/min (high frequency)`);
  }
  if (features.incrementRatio < 1.5 && features.incrementRatio > 0) {
    parts.push(`increment x${features.incrementRatio.toFixed(2)} (minimum-increment scripting)`);
  }
  if (features.sellerCoOccurrence >= 3) {
    parts.push(`${features.sellerCoOccurrence} auctions with same seller (co-occurrence)`);
  }
  if (features.reciprocityScore > 0.3) {
    parts.push(`reciprocity ${(features.reciprocityScore * 100).toFixed(0)}% (collusion ring)`);
  }
  if (parts.length === 0) parts.push(`composite score ${s.toFixed(3)}`);
  return parts.join('; ');
}
