/**
 * Phase A11: code-derived reference docs.
 *
 * Reads the actual source of truth -- prisma/schema.prisma, the route mount
 * table in src/index.ts, the *.routes.ts files those mounts point at, and the
 * Zod schemas in their controllers -- and writes docs/schema.md + docs/api.md.
 *
 * This replaces hand-written API/schema docs (the bible.md drift Phase A exists
 * to kill): the docs can no longer lie because they are regenerated from code.
 * Pure static analysis -- no app boot, no DB, no Prisma client. The Prisma DSL
 * is line-parsed; the TypeScript is walked with the compiler API.
 *
 * Run: npm run docs:generate   (re-run after touching routes / controllers /
 * schema). The graph in graphify-out/ stays the narrative doc; these two files
 * are the flat reference. Output is deterministic (no timestamps) so a re-run
 * only diffs when the code actually changed.
 */
import * as fs from 'fs';
import * as path from 'path';
import * as ts from 'typescript';

const BACK_ROOT = path.resolve(__dirname, '../..');
const REPO_ROOT = path.resolve(__dirname, '../../..');
const SCHEMA_PRISMA = path.join(BACK_ROOT, 'prisma', 'schema.prisma');
const INDEX_TS = path.join(BACK_ROOT, 'src', 'index.ts');
const MODULES_GLOB_ROOT = path.join(BACK_ROOT, 'src', 'modules');
const DOCS_DIR = path.join(REPO_ROOT, 'docs');

const HEADER = (title: string) =>
  `<!-- GENERATED by \`npm run docs:generate\` (back/src/scripts/generate-docs.ts).\n` +
  `     Do not edit by hand -- re-run the generator after changing the code. -->\n\n# ${title}\n`;

// ─── Prisma schema parser (line-based; the Prisma DSL is line-oriented) ────────

interface PField {
  name: string;
  type: string;
  attrs: string;
  note: string;
  isRelation: boolean;
}
interface PModel {
  name: string;
  map: string;
  fields: PField[];
  indexes: string[];
  uniques: string[];
}
interface PEnum {
  name: string;
  values: string[];
}

function parsePrisma(text: string): { models: PModel[]; enums: PEnum[] } {
  const lines = text.split(/\r?\n/);

  const modelNames = new Set<string>();
  const enumNames = new Set<string>();
  for (const l of lines) {
    const mm = l.match(/^\s*model\s+(\w+)\s*\{/);
    if (mm) modelNames.add(mm[1]);
    const em = l.match(/^\s*enum\s+(\w+)\s*\{/);
    if (em) enumNames.add(em[1]);
  }

  const models: PModel[] = [];
  const enums: PEnum[] = [];

  let i = 0;
  while (i < lines.length) {
    const enumM = lines[i].match(/^\s*enum\s+(\w+)\s*\{/);
    const modelM = lines[i].match(/^\s*model\s+(\w+)\s*\{/);

    if (enumM) {
      const e: PEnum = { name: enumM[1], values: [] };
      i++;
      while (i < lines.length && !/^\s*\}/.test(lines[i])) {
        const v = lines[i].replace(/\/\/.*$/, '').trim();
        if (v) e.values.push(v);
        i++;
      }
      enums.push(e);
      i++;
      continue;
    }

    if (modelM) {
      const md: PModel = { name: modelM[1], map: '', fields: [], indexes: [], uniques: [] };
      i++;
      while (i < lines.length && !/^\s*\}/.test(lines[i])) {
        const trimmed = lines[i].trim();
        if (trimmed === '' || trimmed.startsWith('//')) {
          i++;
          continue;
        }
        if (trimmed.startsWith('@@map(')) {
          const mm = trimmed.match(/@@map\("([^"]+)"\)/);
          if (mm) md.map = mm[1];
          i++;
          continue;
        }
        if (trimmed.startsWith('@@index(')) {
          md.indexes.push(trimmed.replace(/^@@index/, '').trim());
          i++;
          continue;
        }
        if (trimmed.startsWith('@@unique(')) {
          md.uniques.push(trimmed.replace(/^@@unique/, '').trim());
          i++;
          continue;
        }
        if (trimmed.startsWith('@@')) {
          i++;
          continue;
        }
        const noteMatch = trimmed.match(/\/\/\s*(.*)$/);
        const note = noteMatch ? noteMatch[1].trim() : '';
        const code = trimmed.replace(/\/\/.*$/, '').trim();
        const fm = code.match(/^(\w+)\s+([A-Za-z0-9_[\]?]+)\s*(.*)$/);
        if (fm) {
          const baseType = fm[2].replace(/[[\]?]/g, '');
          md.fields.push({
            name: fm[1],
            type: fm[2],
            attrs: fm[3].trim(),
            note,
            isRelation: modelNames.has(baseType) && !enumNames.has(baseType),
          });
        }
        i++;
      }
      models.push(md);
      i++;
      continue;
    }
    i++;
  }

  return { models, enums };
}

function renderSchemaDoc(parsed: { models: PModel[]; enums: PEnum[] }): string {
  const { models, enums } = parsed;
  let out = HEADER('Database Schema');
  out += `\nDerived from \`back/prisma/schema.prisma\`. Money columns are \`Decimal @db.Decimal(18,2)\` (exact; never Float).\n`;

  out += `\n## Enums\n`;
  for (const e of enums) {
    out += `\n### ${e.name}\n\n`;
    out += e.values.map((v) => `- \`${v}\``).join('\n') + '\n';
  }

  out += `\n## Models\n`;
  for (const m of models) {
    out += `\n### ${m.name}` + (m.map ? `  — table \`${m.map}\`` : '') + '\n\n';

    const scalars = m.fields.filter((f) => !f.isRelation);
    out += `| Field | Type | Attributes | Notes |\n|---|---|---|---|\n`;
    for (const f of scalars) {
      out += `| \`${f.name}\` | \`${f.type}\` | ${f.attrs ? '`' + f.attrs + '`' : ''} | ${f.note} |\n`;
    }

    const relations = m.fields.filter((f) => f.isRelation);
    if (relations.length) {
      out += `\n**Relations:** ` + relations.map((r) => `\`${r.name}: ${r.type}\``).join(', ') + '\n';
    }
    if (m.uniques.length) {
      out += `\n**Unique:** ` + m.uniques.map((u) => `\`${u}\``).join(', ') + '\n';
    }
    if (m.indexes.length) {
      out += `\n**Indexes:** ` + m.indexes.map((idx) => `\`${idx}\``).join(', ') + '\n';
    }
  }
  return out;
}

// ─── TypeScript AST helpers ────────────────────────────────────────────────────

const sourceCache = new Map<string, ts.SourceFile>();
function parseTs(filePath: string): ts.SourceFile {
  const cached = sourceCache.get(filePath);
  if (cached) return cached;
  const text = fs.readFileSync(filePath, 'utf8');
  const sf = ts.createSourceFile(filePath, text, ts.ScriptTarget.Latest, true);
  sourceCache.set(filePath, sf);
  return sf;
}

function resolveImport(fromDir: string, spec: string): string {
  if (!spec.startsWith('.')) return '';
  const base = path.resolve(fromDir, spec);
  return base.endsWith('.ts') ? base : base + '.ts';
}

// identifier -> resolved .ts path, for default + namespace imports
function buildImportMap(sf: ts.SourceFile, fileDir: string): Map<string, string> {
  const map = new Map<string, string>();
  for (const st of sf.statements) {
    if (!ts.isImportDeclaration(st) || !st.importClause) continue;
    if (!ts.isStringLiteral(st.moduleSpecifier)) continue;
    const resolved = resolveImport(fileDir, st.moduleSpecifier.text);
    if (!resolved) continue;
    if (st.importClause.name) map.set(st.importClause.name.text, resolved);
    const nb = st.importClause.namedBindings;
    if (nb && ts.isNamespaceImport(nb)) map.set(nb.name.text, resolved);
  }
  return map;
}

function isMethodCallOn(node: ts.Node, objName: string, methods: string[]): node is ts.CallExpression {
  return (
    ts.isCallExpression(node) &&
    ts.isPropertyAccessExpression(node.expression) &&
    ts.isIdentifier(node.expression.expression) &&
    node.expression.expression.text === objName &&
    methods.includes(node.expression.name.text)
  );
}

// ─── Route / mount extraction ──────────────────────────────────────────────────

interface RouteDef {
  method: string; // GET/POST/...
  fullPath: string;
  auth: string;
  handler: string; // ns.fn
  controllerFile: string;
  controllerFn: string;
  source?: 'body' | 'query' | 'params';
  fields?: { name: string; rule: string }[];
}
interface RouteGroup {
  prefix: string;
  file: string;
  routes: RouteDef[];
}

const HTTP = ['get', 'post', 'put', 'delete', 'patch'];

function middlewareName(arg: ts.Node, sf: ts.SourceFile): string {
  if (ts.isIdentifier(arg)) return arg.text;
  return arg.getText(sf);
}

function authLabel(middleware: string[]): string {
  let label = 'Public';
  if (middleware.includes('authenticate')) label = 'Auth';
  if (middleware.includes('requireAdmin')) label = 'Admin';
  if (middleware.includes('strictRateLimiter')) label += ' (rate-limited)';
  return label;
}

function joinPath(prefix: string, routePath: string): string {
  if (routePath === '/' || routePath === '') return prefix;
  return prefix + routePath;
}

function extractRoutes(prefix: string, file: string): RouteGroup {
  const sf = parseTs(file);
  const imports = buildImportMap(sf, path.dirname(file));
  const group: RouteGroup = { prefix, file: path.relative(BACK_ROOT, file).replace(/\\/g, '/'), routes: [] };

  const baseMiddleware: string[] = [];

  for (const st of sf.statements) {
    if (!ts.isExpressionStatement(st)) continue;
    const call = st.expression;
    if (!isMethodCallOn(call, 'router', [...HTTP, 'use'])) continue;
    const method = (call.expression as ts.PropertyAccessExpression).name.text;
    const args = call.arguments;

    if (method === 'use') {
      // router.use(authenticate[, requireAdmin]) -- baseline for routes below it.
      for (const a of args) baseMiddleware.push(middlewareName(a, sf));
      continue;
    }

    if (args.length === 0 || !ts.isStringLiteral(args[0])) continue;
    const routePath = args[0].text;
    const rest = args.slice(1);
    if (rest.length === 0) continue;
    const handlerArg = rest[rest.length - 1];
    const routeMw = rest.slice(0, -1).map((a) => middlewareName(a, sf));

    let ns = '';
    let fn = '';
    if (ts.isPropertyAccessExpression(handlerArg) && ts.isIdentifier(handlerArg.expression)) {
      ns = handlerArg.expression.text;
      fn = handlerArg.name.text;
    } else if (ts.isIdentifier(handlerArg)) {
      fn = handlerArg.text;
    } else {
      continue;
    }

    const route: RouteDef = {
      method: method.toUpperCase(),
      fullPath: joinPath(prefix, routePath),
      auth: authLabel([...baseMiddleware, ...routeMw]),
      handler: ns ? `${ns}.${fn}` : fn,
      controllerFile: ns ? imports.get(ns) || '' : '',
      controllerFn: fn,
    };

    if (route.controllerFile && fs.existsSync(route.controllerFile)) {
      const schema = extractZodSchema(route.controllerFile, fn);
      if (schema) {
        route.source = schema.source;
        route.fields = schema.fields;
      }
    }
    group.routes.push(route);
  }
  return group;
}

// ─── Zod schema extraction from a controller handler ───────────────────────────

function findExportedFn(sf: ts.SourceFile, name: string): ts.Node | undefined {
  for (const st of sf.statements) {
    if (!ts.isVariableStatement(st)) continue;
    const isExported = st.modifiers?.some((m) => m.kind === ts.SyntaxKind.ExportKeyword);
    if (!isExported) continue;
    for (const d of st.declarationList.declarations) {
      if (
        ts.isIdentifier(d.name) &&
        d.name.text === name &&
        d.initializer &&
        (ts.isArrowFunction(d.initializer) || ts.isFunctionExpression(d.initializer))
      ) {
        return d.initializer;
      }
    }
  }
  return undefined;
}

// find a `<x>.parse(req.body|query|params)` call; return the `<x>` node + source
function findParseTarget(
  fnNode: ts.Node,
  sf: ts.SourceFile
): { target: ts.Expression; source: 'body' | 'query' | 'params' } | undefined {
  let found: { target: ts.Expression; source: 'body' | 'query' | 'params' } | undefined;
  const visit = (n: ts.Node): void => {
    if (found) return;
    if (
      ts.isCallExpression(n) &&
      ts.isPropertyAccessExpression(n.expression) &&
      n.expression.name.text === 'parse' &&
      n.arguments.length > 0
    ) {
      const m = n.arguments[0].getText(sf).match(/^req\.(body|query|params)/);
      if (m) {
        found = { target: n.expression.expression, source: m[1] as 'body' | 'query' | 'params' };
        return;
      }
    }
    ts.forEachChild(n, visit);
  };
  visit(fnNode);
  return found;
}

// resolve an identifier to its const initializer (local scope first, then module)
function resolveConstInit(name: string, scope: ts.Node, sf: ts.SourceFile): ts.Expression | undefined {
  let local: ts.Expression | undefined;
  const visit = (n: ts.Node): void => {
    if (local) return;
    if (ts.isVariableDeclaration(n) && ts.isIdentifier(n.name) && n.name.text === name && n.initializer) {
      local = n.initializer;
      return;
    }
    ts.forEachChild(n, visit);
  };
  visit(scope);
  if (local) return local;

  for (const st of sf.statements) {
    if (!ts.isVariableStatement(st)) continue;
    for (const d of st.declarationList.declarations) {
      if (ts.isIdentifier(d.name) && d.name.text === name && d.initializer) return d.initializer;
    }
  }
  return undefined;
}

// descend into an expression to find the `z.object({...})` object literal
function findZodObjectLiteral(node: ts.Node): ts.ObjectLiteralExpression | undefined {
  let result: ts.ObjectLiteralExpression | undefined;
  const visit = (n: ts.Node): void => {
    if (result) return;
    if (
      ts.isCallExpression(n) &&
      ts.isPropertyAccessExpression(n.expression) &&
      n.expression.name.text === 'object' &&
      ts.isIdentifier(n.expression.expression) &&
      n.expression.expression.text === 'z' &&
      n.arguments.length > 0 &&
      ts.isObjectLiteralExpression(n.arguments[0])
    ) {
      result = n.arguments[0];
      return;
    }
    ts.forEachChild(n, visit);
  };
  visit(node);
  return result;
}

function extractZodSchema(
  controllerFile: string,
  fnName: string
): { source: 'body' | 'query' | 'params'; fields: { name: string; rule: string }[] } | undefined {
  const sf = parseTs(controllerFile);
  const fnNode = findExportedFn(sf, fnName);
  if (!fnNode) return undefined;

  const parseTarget = findParseTarget(fnNode, sf);
  if (!parseTarget) return undefined;

  let objLit: ts.ObjectLiteralExpression | undefined;
  if (ts.isIdentifier(parseTarget.target)) {
    const init = resolveConstInit(parseTarget.target.text, fnNode, sf);
    if (init) objLit = findZodObjectLiteral(init);
  } else {
    objLit = findZodObjectLiteral(parseTarget.target);
  }
  if (!objLit) return undefined;

  const fields: { name: string; rule: string }[] = [];
  for (const p of objLit.properties) {
    if (ts.isPropertyAssignment(p)) {
      fields.push({
        name: p.name.getText(sf).replace(/['"]/g, ''),
        rule: p.initializer.getText(sf).replace(/\s+/g, ' '),
      });
    }
  }
  return { source: parseTarget.source, fields };
}

// ─── index.ts mount table + root-level routes ──────────────────────────────────

interface RootRoute {
  method: string;
  fullPath: string;
}

function extractMounts(): { groups: RouteGroup[]; rootRoutes: RootRoute[]; mountedFiles: Set<string> } {
  const sf = parseTs(INDEX_TS);
  const imports = buildImportMap(sf, path.dirname(INDEX_TS));
  const groups: RouteGroup[] = [];
  const rootRoutes: RootRoute[] = [];
  const mountedFiles = new Set<string>();

  const visit = (n: ts.Node): void => {
    if (isMethodCallOn(n, 'app', ['use'])) {
      const a = n.arguments;
      if (a.length >= 2 && ts.isStringLiteral(a[0]) && ts.isIdentifier(a[1])) {
        const prefix = a[0].text;
        if (prefix.startsWith('/api')) {
          const file = imports.get(a[1].text);
          if (file && fs.existsSync(file)) {
            mountedFiles.add(file);
            groups.push(extractRoutes(prefix, file));
          }
        }
      }
    } else if (isMethodCallOn(n, 'app', HTTP)) {
      const a = n.arguments;
      if (a.length >= 1 && ts.isStringLiteral(a[0])) {
        rootRoutes.push({
          method: (n.expression as ts.PropertyAccessExpression).name.text.toUpperCase(),
          fullPath: a[0].text,
        });
      }
    }
    ts.forEachChild(n, visit);
  };
  visit(sf);
  return { groups, rootRoutes, mountedFiles };
}

function renderApiDoc(
  groups: RouteGroup[],
  rootRoutes: RootRoute[],
  deadRouteFiles: string[]
): string {
  let out = HEADER('HTTP API');
  out += `\nDerived from the \`app.use('/api/...', ...)\` mount table in \`back/src/index.ts\`, the mounted \`*.routes.ts\` files, and the Zod schemas each handler runs. **Auth** column: \`Public\` = no token; \`Auth\` = JWT required; \`Admin\` = JWT + admin role.\n`;

  if (rootRoutes.length) {
    out += `\n## Root\n\n| Method | Path |\n|---|---|\n`;
    for (const r of rootRoutes) out += `| ${r.method} | \`${r.fullPath}\` |\n`;
  }

  for (const g of groups) {
    out += `\n## \`${g.prefix}\`  — ${g.file}\n\n`;
    out += `| Method | Path | Auth | Handler | Request |\n|---|---|---|---|---|\n`;
    for (const r of g.routes) {
      const req = r.fields && r.fields.length ? `${r.source}` : '—';
      out += `| ${r.method} | \`${r.fullPath}\` | ${r.auth} | \`${r.handler}\` | ${req} |\n`;
    }

    const withSchema = g.routes.filter((r) => r.fields && r.fields.length);
    if (withSchema.length) {
      out += `\n#### Request schemas\n`;
      for (const r of withSchema) {
        out += `\n**${r.method} \`${r.fullPath}\`** (${r.source})\n`;
        for (const f of r.fields!) out += `- \`${f.name}\`: \`${f.rule}\`\n`;
      }
    }
  }

  if (deadRouteFiles.length) {
    out += `\n## Defined but not mounted\n\nThese \`*.routes.ts\` files exist but no \`app.use\` in \`index.ts\` references them — dead until mounted:\n\n`;
    for (const f of deadRouteFiles) out += `- \`${f}\`\n`;
  }

  return out;
}

// ─── Run ───────────────────────────────────────────────────────────────────────

function listRouteFiles(): string[] {
  const out: string[] = [];
  const walk = (dir: string): void => {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) walk(full);
      else if (entry.name.endsWith('.routes.ts')) out.push(full);
    }
  };
  walk(MODULES_GLOB_ROOT);
  return out;
}

function main(): void {
  fs.mkdirSync(DOCS_DIR, { recursive: true });

  const schemaParsed = parsePrisma(fs.readFileSync(SCHEMA_PRISMA, 'utf8'));
  const schemaDoc = renderSchemaDoc(schemaParsed);
  fs.writeFileSync(path.join(DOCS_DIR, 'schema.md'), schemaDoc);
  console.log(`schema.md: ${schemaParsed.models.length} models, ${schemaParsed.enums.length} enums`);

  const { groups, rootRoutes, mountedFiles } = extractMounts();
  const allRouteFiles = listRouteFiles();
  const deadRouteFiles = allRouteFiles
    .filter((f) => !mountedFiles.has(f))
    .map((f) => path.relative(BACK_ROOT, f).replace(/\\/g, '/'));
  const apiDoc = renderApiDoc(groups, rootRoutes, deadRouteFiles);
  fs.writeFileSync(path.join(DOCS_DIR, 'api.md'), apiDoc);
  const routeCount = groups.reduce((n, g) => n + g.routes.length, 0);
  console.log(`api.md: ${routeCount} routes across ${groups.length} mounts, ${deadRouteFiles.length} dead route file(s)`);

  console.log(`Wrote docs to ${path.relative(REPO_ROOT, DOCS_DIR) || 'docs'}/`);
}

main();
