# =============================================================================
# Canonical k6 throughput sweep
# =============================================================================
# Runs the six configurations that back paper/main.tex Table III and
# paper/supplementary.tex Table XII: VUs in {1, 10, 100} crossed with MODE in
# {direct, stream}. Each run is 15 seconds. The raw output of each run is
# appended to docs/rp/rp-audit-02-k6-canonical-<timestamp>.md with a header
# capturing the auction id, JWT, and git commit hash so the artefact is fully
# auditable.
#
# Usage (PowerShell):
#   $env:SIM_TOKEN = "<jwt token from POST /api/auth/login>"
#   $env:AUCTION_ID = "<active auction uuid>"
#   .\packages\simulator\k6\run-canonical.ps1
#
# Prerequisites:
#   - Backend running on http://localhost:5000, started with the benchmark env
#     so the numbers are clean (no rate-limit 429s, stream consumer running, no
#     backpressure 503s):
#       $env:RATE_LIMIT_MAX="100000000"; $env:BID_SEQUENCER="true"; `
#         $env:BID_STREAM_BACKPRESSURE="100000"; npm run dev:back
#   - A fresh JWT obtained (set SIM_TOKEN) and an ACTIVE auction owned by a
#     different user (set AUCTION_ID) -- `npm run db:prepare-bench` prints both.
#   - k6 is on PATH
#
# If any run reports bid_errors > 0, the backend was not started with the env
# above and those numbers are contaminated -- restart and re-run.
#
# Output:
#   docs/rp/rp-audit-02-k6-canonical-<YYYYMMDD-HHMM>.md
# =============================================================================

$ErrorActionPreference = 'Stop'

if (-not $env:SIM_TOKEN) {
  Write-Error "SIM_TOKEN env var not set. Login first and export the JWT."
  exit 1
}
if (-not $env:AUCTION_ID) {
  Write-Error "AUCTION_ID env var not set. Create an active auction first."
  exit 1
}

$timestamp = Get-Date -Format "yyyyMMdd-HHmm"
$outPath = "docs/rp/rp-audit-02-k6-canonical-$timestamp.md"
$gitSha = (git rev-parse --short HEAD 2>$null)
if (-not $gitSha) { $gitSha = "unknown" }

$header = @"
# k6 Canonical Throughput Sweep ($timestamp)

- Git commit: ``$gitSha``
- Auction id: ``$env:AUCTION_ID``
- Backend: http://localhost:5000
- k6 script: packages/simulator/k6/bid-throughput.js
- Duration per run: 15 seconds
- Configurations: VUs in {1, 10, 100} x MODE in {direct, stream}

This file is generated by ``packages/simulator/k6/run-canonical.ps1`` and is meant to be the auditable source-of-truth artefact behind ``paper/figures/k6_results.json``. Treat it as append-only history.

"@

Set-Content -Path $outPath -Value $header -Encoding utf8

$configs = @(
  @{ Vus = 1;   Mode = 'direct' },
  @{ Vus = 10;  Mode = 'direct' },
  @{ Vus = 100; Mode = 'direct' },
  @{ Vus = 1;   Mode = 'stream' },
  @{ Vus = 10;  Mode = 'stream' },
  @{ Vus = 100; Mode = 'stream' }
)

foreach ($c in $configs) {
  $sectionHeader = "`n## MODE=$($c.Mode), VUS=$($c.Vus)`n"
  Add-Content -Path $outPath -Value $sectionHeader -Encoding utf8

  Add-Content -Path $outPath -Value '```' -Encoding utf8
  $log = k6 run packages/simulator/k6/bid-throughput.js `
    -e SIM_TOKEN="$env:SIM_TOKEN" `
    -e AUCTION_ID="$env:AUCTION_ID" `
    -e VUS="$($c.Vus)" `
    -e DURATION="15s" `
    -e MODE="$($c.Mode)" 2>&1

  $log | Out-File -FilePath $outPath -Append -Encoding utf8
  Add-Content -Path $outPath -Value '```' -Encoding utf8

  # Brief pause so the backend can drain between runs.
  Start-Sleep -Seconds 3
}

Write-Host "Sweep complete. Output: $outPath"
Write-Host "Update paper/figures/k6_results.json by hand if these numbers diverge."
